### ISSUE TITLE
[バグ] バグメモリスターを使用し、とあるMOBが出現した際にエラー落ちする。(v13α2)

### ISSUE THREAD

**Issue by FreyCielu** [TUSB/TheUnusualSkyBlock#166]
### 発生したTUSBv13のVersion

v13.1.1α

### 概要

v13α2に於いて、釣り等で手に入れられるバグメモリスターを使用し、確率で出現するアサルトウォーデンが出現した際、添付画像のようなエラーが発生しワールドから蹴られる。
![image](https://github.com/TUSB/TheUnusualSkyBlock/assets/69429398/5f93e117-b0a4-456f-af7f-2acdc4c1cce3)

### 再現方法

1. バグメモリスターを使用する。
2. アサルトウォーデンが出現する。
3. エラーを吐きワールドからログアウトさせられる。

### ログ

* 以下はサーバーログです。
```
[22:05:52] [Netty Server IO #10/ERROR]: Error receiving packet 38
java.lang.IllegalStateException: Unable to get entityId from uuid
	at dfy.a(SourceFile:70) ~[server-1.19.4.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.6.jar:?]
	at dfy.a(SourceFile:68) ~[server-1.19.4.jar:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-6.0.6.jar:?]
	at dfy.c(SourceFile:66) ~[server-1.19.4.jar:?]
	at dfy$a.a(SourceFile:90) ~[server-1.19.4.jar:?]
	at dfy$a.a(SourceFile:82) ~[server-1.19.4.jar:?]
	at dgf.a(SourceFile:32) ~[server-1.19.4.jar:?]
	at iy.a(SourceFile:59) ~[server-1.19.4.jar:?]
	at ws.a(SourceFile:65) ~[server-1.19.4.jar:?]
	at sw.a(SourceFile:45) ~[server-1.19.4.jar:?]
	at sw.encode(SourceFile:14) ~[server-1.19.4.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at sq.a(SourceFile:215) ~[server-1.19.4.jar:?]
	at sq.b(SourceFile:207) ~[server-1.19.4.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:05:52] [Server thread/INFO]: FreyCielu lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Unable to get entityId from uuid
```

**Comment by waxsd100** [comment]
https://www.reddit.com/r/MinecraftCommands/comments/14izuud/i_keep_getting_kicked_from_my_server_for_internal/

**Comment by NePonpon** [comment]
# 再現方法についての補足
アサルトウォーデンの罠を捨てた場合、プレイヤーと同じ座標に召喚されるが、この場合だとエラー落ちする。
ディスペンサーに詰めて罠を使った場合、エラー落ちすることがない。
ディスペンサーに詰めて罠を使った場合でも、アイテムを出した後に拾わない程度に近づいた状態だと再現が可能になる。

# 原因
アサルトウォーデンに設定された`listener.selector`が悪影響を及ぼしていた。

## 通常のウォーデン
```mcfunction
summon warden
```
> ただし、自然湧きの処理をコメントアウトする必要がある。

summonコマンドで召喚した通常のウォーデンの`listener.selector`は以下のようになっている。
```
listener: {
	selector: {
		tick: -1L
	}
}
```

## アサルトウォーデン
```mcfunction
loot give @s loot item:item/firework_star/etc/trap_spawn_assault_warden
```
> アサルトウォーデンの罠のコマンド

アサルトウォーデンの`listener.selector`は以下のようになっている。
```
listener:{
	selector:{
		event:{
			distance:2.226483f,
			game_event:"minecraft:entity_place",
			pos:[-3778.5d,19.5d,828.5d],
			source:[I;-1370743864,-1129364455,-1521016688,-729109770]
 	   },
 	   tick:343412370L
  }
}
```
`event`というタグが増えていた。
`distance`と`game_event`については詳細が分からなかったが、
`pos`はアサルトウォーデンが召喚された座標、`tick`はgametimeを示している。

`source`は何かのエンティティのUUIDを示していることが分かる。

このエンティティは、Mob召喚用スポナーから出てくる、アサルトウォーデン本体が乗っている経験値オーブであることが調査で分かった。
`source`のUUIDを使用して経験値オーブとの連携した処理が実行されることが予想される。

その中でプレイヤーが経験値オーブを取得してしまい、`source`の示すエンティティがいなくなったときにこのエラー落ちが発生すると結論付けられた。

# 解決
アサルトウォーデンのCallOnInitの中で以下のコマンドを実行する。
```mcfunction
data modify entity @s listener.selector set value {tick:-1L}
```
通常のウォーデンが持つNBTに上書きすることで、経験値オーブが消えてもエラー落ちしないようにすることができた。

# 修正コミット
a00291b
